name: CI

on: 
 push:
  branches:
    - main
    - "feature/**"

 pull_request:
   branches:
     - main
     

jobs:
 sast_scan:
   name: Run Bandit Scan
   runs-on: ubuntu-latest

   steps:
   - name: Checkout code
     uses: actions/checkout@v4

   - name: Setup Python
     uses: actions/setup-python@v5
     with:
       python-version: "3.11"
       cache: pip

   - name: Install Bandit
     run: pip install bandit

   - name: Run Bandit Scan (Console)
     run: bandit -r . -ll -ii --exit-zero

   - name: Generate JSON Report
     run: bandit -r . -f json -o bandit-report.json --exit-zero

   - name: Upload Artifact
     uses: actions/upload-artifact@v4
     if: always()
     with:
       name: bandit-findings
       path: bandit-report.json

 dependency_scan:
   name: Run Dependency Scan
   runs-on: ubuntu-latest

   steps:
   - name: Checkout code
     uses: actions/checkout@v4

   - name: Setup Python
     uses: actions/setup-python@v5
     with:
       python-version: "3.11"
       cache: pip 

   - name: Install Project Dependencies
     run: pip install -r requirements.txt

   - name: Install pip-audit
     run: pip install pip-audit

   - name: Run pip-audit
     run: pip-audit -f json -o pip-audit-report.json || true

   - name: Upload Artifact
     uses: actions/upload-artifact@v4
     if: always()
     with:
       name: pip-audit-findings
       path: pip-audit-report.json
       

 image_scan:
   name: Build Image and Run Image Scan
   runs-on: ubuntu-latest

   steps:
   - name: Checkout code
     uses: actions/checkout@v4

   - name: Build Docker Image
     run: docker build -f Dockerfile -t myapp:latest .

#   - name: Docker Scout Scan
#     run: |
#       curl -fsSL https://raw.githubusercontent.com/docker/scout-cli/main/install.sh -o install-scout.sh
#       sh install-scout.sh
#       echo ${{ secrets.REPO_PWD }} | docker login -u ${{ secrets.REPO_USER }} --password-stdin
#       docker scout quickview
#       docker scout cves

   - name: Docker Scout Scan
     uses: docker/scout-action@v1
     with:
       dockerhub-user: ${{ secrets.REPO_USER }}
       dockerhub-password: ${{ secrets.REPO_PWD }}
       image: local://myapp:latest
       command: quickview,cves
       only-severities: critical,high
       sarif-file: scout-report.sarif

   - name: Upload Artifact
     uses: actions/upload-artifact@v4
     if: always()
     with:
       name: docker-scout-findings
       path: scout-report.sarif




   

   
